# Changes here will be overwritten by Copier
_commit: 9f942cd
_src_path: .
copyright_year: '2025'
documentation: true
email: ''
full_name: Avengineers
github_username: Avengineers
main_branch: develop
open_source_license: MIT
package_name: sple_artifacts_uploader
project_name: SPLE Artifacts Uploader
project_short_description: 'Configurable and automatable uploader for artifacts.'
project_slug: sple-artifacts-uploader

